// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///  VAPID key for web
const vapidKey =
    "BGmzYtRIxH2IxDISwwj0bOWsu2yrGDiPHTmwt_Tb1FBlpwmT5HfGzGeRu6Ruz0oqw9IxeX50Fl-GOBuE_svSjPc";

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDq-WNCJGncX7Z8A2Mlw9dEuaUQuVC3uY',
    appId: '1:1015324588991:web:a8cfb119423a0bb569bf0a',
    messagingSenderId: '1015324588991',
    projectId: 'tenneo-78be6',
    authDomain: 'tenneo-78be6.firebaseapp.com',
    storageBucket: 'tenneo-78be6.appspot.com',
    measurementId: 'G-1YJFTGMCH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5oLJIMFFYuKuoI2otP_N8v-6Z40ISnx8',
    appId: '1:1015324588991:android:a9f0ba5e2c5969f069bf0a',
    messagingSenderId: '1015324588991',
    projectId: 'tenneo-78be6',
    storageBucket: 'tenneo-78be6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHQpYe5Gv9cytQdms5HP4erqoUekb4LfE',
    appId: '1:1015324588991:ios:49277da529e8b2b669bf0a',
    messagingSenderId: '1015324588991',
    projectId: 'tenneo-78be6',
    storageBucket: 'tenneo-78be6.appspot.com',
    iosClientId:
        '1015324588991-lu8cnnd272ordp9uc5me2qr13m9dl04t.apps.googleusercontent.com',
    iosBundleId: 'com.tenneo.lms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHQpYe5Gv9cytQdms5HP4erqoUekb4LfE',
    appId: '1:1015324588991:ios:a7a6c7786e0260ff69bf0a',
    messagingSenderId: '1015324588991',
    projectId: 'tenneo-78be6',
    storageBucket: 'tenneo-78be6.appspot.com',
    iosClientId:
        '1015324588991-tnbh0e6t35hma9okcpsnt893hf7unnm7.apps.googleusercontent.com',
    iosBundleId: 'com.tenneo.lms.RunnerTests',
  );
}
